#!/bin/bash
echo "Testing tidy command..."
CMD="$SKILL_DIR/commands/tidy.md"
assert_file_exists "$CMD" "tidy.md exists"
assert_contains "$CMD" "Inbox" "scans Inbox directory"
assert_contains "$CMD" -- "--dry-run" "supports --dry-run flag"
assert_contains "$CMD" -- "--to" "supports --to flag"
assert_contains "$CMD" -- "--mode" "supports mode selection"
assert_contains "$CMD" -i "strong" "documents strong tidy mode"
assert_contains "$CMD" -i "git" "has git safety baseline for strong mode"
assert_contains "$CMD" -i "hidden\\|\\.obsidian\\|dot" "excludes hidden/system directories"
assert_contains "$CMD" -i "legacy\\|digital-hub\\|private\\|_drafts" "supports legacy content directories"
assert_contains "$CMD" -i "rename\\|未命名\\|draft-" "supports automatic renaming strategy"
assert_contains "$CMD" -- "--force-retidy" "supports force retidy override"
assert_contains "$CMD" -- "--force-rename" "supports force rename override"
assert_contains "$CMD" -i "project-policy\\|contain\\|split" "supports project containment policy"
assert_contains "$CMD" -i "冻结结构\\|不改内部层级\\|不改.*文件名" "freezes project structure in contain mode"
assert_contains "$CMD" -i "\\.obos/tidy-state\\.json" "stores idempotency state in .obos"
assert_contains "$CMD" -i "\\.obos/tidy-config\\.json\\|projectRootsExtra" "supports project extra roots config"
assert_contains "$CMD" -i "dirEvaluation\\.enabled\\|目录必要性评估" "supports directory necessity evaluation toggle"
assert_contains "$CMD" -i "protectedRoots\\|Templates\\|Attachments\\|Excalidraw" "supports protected roots for directory cleanup"
assert_contains "$CMD" -i "projectDecisionMode\\|interactive\\|逐个.*询问" "supports interactive project directory decisions"
assert_contains "$CMD" -i "thresholds\\|keep\\|reorganize\\|70\\|40" "supports three-tier scoring thresholds"
assert_contains "$CMD" -i "archiveRoot\\|_archive" "supports archive root for low-necessity directories"
assert_contains "$CMD" -i "deleteMarkdown\\|false\\|不删.*markdown" "disables markdown deletion by default"
assert_contains "$CMD" -i "autoDeleteEmptyDirs\\|空目录.*删除" "supports automatic empty directory cleanup"
assert_contains "$CMD" -i "dir-audit\\.json" "writes directory audit output"
assert_contains "$CMD" -i "KEEP\\|REORGANIZE\\|ARCHIVE_DIR" "supports three directory actions by score"
assert_contains "$CMD" -i "name_locked" "locks manual rename decisions"
assert_contains "$CMD" -i "review_needed" "marks low-confidence notes for review"
assert_contains "$CMD" -i "损坏\\|corrupt\\|强制.*dry-run" "handles corrupted state with forced dry-run"
assert_contains "$CMD" "AskUserQuestion" "uses AskUserQuestion for confirmation"
assert_contains "$CMD" "Notes/" "classifies to Notes"
assert_contains "$CMD" "Clippings/" "classifies to Clippings"
assert_contains "$CMD" "References/" "classifies to References"
assert_contains "$CMD" "sync" "triggers sync after tidy"
